### ISSUE TITLE
Feature request: color text for the "MISSING" warning

### ISSUE THREAD

**Issue by stevenhoneyman** [juster/treeldd#1]
I really like this script, it's much faster than lddtree (pax-utils). I made two changes to it though, one just to flip the -s option (show by default instead of hide)- but that's just personal preference. The other is to add some colour/boldness to the missing text. My ugly no-perl-knowledge way looks like this, but I'm sure Term::ANSIColor or something would be more appropriate:

``` diff
@@ -254,7 +254,7 @@

         my $new_node = ( $file_fqp
                          ? [ [ $file_or_lib, $file_fqp ] ]
-                         : [ [ ("*MISSING* $file_or_lib") x 2 ] ] );
+                         : [ [ ("\e[1;97m$file_or_lib\e[5;91m MISSING\e[0m") x 2 ] ] );

         $node_of{$file_or_lib} = $new_node;

```

(the red text blinks on blink-enabled terminals)
![2014-10-11_t162829_278x195_scrot](https://cloud.githubusercontent.com/assets/7693796/4603096/63ec3ac4-515b-11e4-8fc9-90578ba1ceb9.png)

**Comment by juster** [comment]
Thanks! I'll add that for you soon. Feel free to fork this and adopt it as your own if you wish. I haven't used treeldd in years and I am a bit shocked at how pretentious my coding style was. Sorry you had to read that.

Here is a minimal version in awk, if you like that better: https://gist.github.com/juster/94c3342a645938c8a026

**Comment by juster** [comment]
Oh wow! I forgot to close this after I applied the changes.
